# -*- coding: utf-8 -*-
"""Assignment_21st.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QpP5Ffu8L8VcPx5zHThKXhs5N6Y_8-5v

Writing a file and inserting 5 lines using a loop
"""

with open("loop.txt","w") as f:
  count =0
  while count <5 :
    f.write("first line has Python\n")
    f.write("second line\n")
    f.write("third line has Python\n")
    f.write("fourth line has Python\n")
    f.write("fifth line\n")
    count +=1

with open("loop.txt","r") as f:
  print(f.read())

"""Read lines consisting only "Python"
"""

with open("loop.txt","r") as f:
    for lines in f:
      if "Python" in lines:
        print(lines)

"""Count characters in file"""

with open("count.txt", "w") as f:
  f.write("I have 2800 characters")

with open("count.txt","r") as f:
  char=f.read()
  print("Total characters:", len(char))

"""Append current date, time in a *file*"""

from datetime import datetime
with open("log.txt","a") as log:
  now = datetime.now()
  log.write("\nDate & Time:"+now.strftime("%d/%m/%Y %I:%M:%S %p"))

with open("log.txt","r") as log:
  print(log.read())

"""Creating folder and saving 3 files in it

"""

import os


Assignments = "Assignments"

if not os.path.exists(Assignments):
    os.mkdir(Assignments)

print(f"Folder '{Assignments}' created successfully.")

import shutil

files=["count.txt","log.txt","loop.txt"]
for file in files:
  shutil.move(file, os.path.join(Assignments, file))

for file in os.listdir(Assignments):
  if file.endswith (".txt"):
    print(file)

